#! /usr/bin/env bash
APPEND=0
while getopts ":a" OPTION
  do 
    case $OPTION in
      a)
        APPEND=1
	      shift
    esac
  done

pat="^\+\s\[.+\]\s(.*)($1)(.*)$"
todo="~/.todo/.todo"
xx $(  cat "${todo}" | sed -r -n "s/${pat}/\1\2\3/1p" | tail -1 )
if [ "$APPEND" -eq "1" ]
then
    ++ $( cat "${todo}" | sed -r -n "s/${pat}/\1\2\3 $2/1p" | tail -1 ) 
else
  ++ $( cat "${todo}" | sed -r -n "s/${pat}/\1$2\3/1p" | tail -1 )
fi

